- name: install pip3
  apt:
    name: "{{ item }}"
    update_cache : yes
  register: result
  until: result is success
  retries: "{{ pkg_retry_num }}"
  delay: "{{ pkg_retry_delay }}"
  with_items: 
    - python3-pip
    - jq

- name: install ansible pull dependcies  
  pip:
    name: "{{ item }}"
  register: result
  until: result is success
  retries: "{{ pkg_retry_num }}"
  delay: "{{ pkg_retry_delay }}"
  with_items:
    - awscli
    - boto3
    - ansible

- name: stop the apt-daily and apt-daily-upgrade timers from triggering
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - apt-daily.timer
    - apt-daily-upgrade.timer
  when: ansible_distribution_major_version == '18'
