ghost_user: ghost
ghost_group: ghost
ghost_uid: 10001
env_name: dev

service_dir: /opt/services/ghost
ghost_dns: "www.farhan.specialpotato.net"
ghost_port: 2368

GHOST_DB_HOST: rds.farhan.specialpotato.net
GHOST_DB_PORT: 3306
GHOST_DB_USER: "{{ lookup('aws_ssm', '/{{ env_name }}/ghost/rds/username', region='us-east-1' ) }}"
GHOST_DB_PW: "{{ lookup('aws_ssm', '/{{ env_name }}/ghost/rds/password', region='us-east-1' ) }}"
GHOST_DB_DBNAME: ghost
    