---
- name: enable concourse-master
  systemd: 
    name: concourse-master
    daemon_reload: yes
    enabled: yes

- name: start concourse-master
  systemd: 
    name: concourse-master
    daemon_reload: yes
    state: started 

- name: restart concourse-master
  systemd: 
    name: concourse-master
    daemon_reload: yes
    state: restarted

- name: enable concourse-worker
  systemd: 
    name: concourse-worker
    daemon_reload: yes
    enabled: yes

- name: start concourse-worker
  systemd: 
    name: concourse-worker
    daemon_reload: yes
    state: started 

- name: restart concourse-worker
  systemd: 
    name: concourse-worker
    daemon_reload: yes
    state: restarted