---
- name: enable ghost
  systemd: 
    name: ghost
    daemon_reload: yes
    enabled: yes

- name: start ghost 
  systemd:
    name: ghost
    daemon_reload: yes
    state: started 

- name: restart ghost 
  systemd:
    name: ghost
    daemon_reload: yes
    state: restarted 

- name: restart nginx 
  systemd:
    name: nginx
    daemon_reload: yes
    state: restarted 