---
jobs:
- name: ami-destroyer
  public: false
  plan:
  - get: my-timer
    trigger: true
  - task: ami-destroyer
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: starseed/amidestroyer
          tag: latest
      run:
        path: sh
        args:
        - -exc
        - |
          cd /code && python3 amidestroyer.py tag:Curate --retain=((retain)) --regions=((regions))
resources:
- name: my-timer
  type: time
  source:
    interval: 24h