---
jobs:
- name: build-ami
  public: false
  plan:
  - get: lcrepo
    trigger: true
  - task: packer-build
    config: 
      inputs:
        - name: lcrepo
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: fkhan2/packer 
      run: 
        path: sh
        args: 
        - -exc
        - | 
          cd lcrepo/ansible && packer build ((packer-template))
      
resources: 
- name: lcrepo
  type: git
  source:
    uri: https://github.com/Farhankhan00/LearningCode.git
    branch: master
