---
jobs:
- name: build-artifact
  public: false
  plan:
  - get: sbrepo
    trigger: true
  - task: go-test
    config: 
      inputs:
        - name: sbrepo
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: concourse/static-golang 
      run: 
        path: sh
        args: 
        - -exc
        - | 
          cd sbrepo && go test ./... 
  - task: go-build
    config: 
      inputs:
        - name: sbrepo
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: concourse/static-golang 
      run: 
        path: sh
        args: 
        - -exc
        - | 
          cd sbrepo && go build .
      
resources: 
- name: sbrepo
  type: git
  source:
    uri: https://github.com/Farhankhan00/snippetbox.git
    branch: dev
    username: ((github-user))
    password: ((github-pat))