- hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    # - name: install python 2
    #   raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - name: gather facts
      setup:
    
  roles:
    - { role: swap }
    - { role: webserver }
    - { role: nodejs }
    - { role: ghost, tags: ["ghost"] }

