---
- name: enable sumologic
  systemd: 
    name: sumologic
    daemon_reload: yes
    enabled: yes

- name: start sumologic 
  systemd:
    name: sumologic
    daemon_reload: yes
    state: started 

- name: restart sumologic 
  systemd:
    name: sumologic
    daemon_reload: yes
    state: restarted 